name: nippo
description: This is a daily report app, and it's a sample app using Flutter and Firebase.

version: 1.0.0+1

environment:
  sdk: '^3.0.0'

dependencies:
  cloud_firestore: ^4.8.1
  cupertino_icons: ^1.0.5
  email_validator: ^2.1.17
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_ui_auth: ^1.4.3
  flutter:
    sdk: flutter
  flutter_overboard: ^3.1.1
  flutter_state_notifier: ^0.7.3
  freezed_annotation: ^2.2.0
  gap: ^3.0.0
  go_router: ^8.0.5
  google_fonts: ^5.0.0
  google_sign_in: ^6.1.4
  hooks_riverpod: ^2.3.6
  intl: ^0.18.0
  modal_progress_hud_nsn: ^0.4.0
  provider: ^6.0.5
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.1.2
  state_notifier: ^0.7.2+1
  tsuruo_kit: ^0.1.1
  url_launcher: ^6.1.11

dev_dependencies:
  build_runner: ^2.4.5
  custom_lint: ^0.4.0
  flutter_gen: ^5.3.1
  flutter_gen_runner: ^5.3.1
  freezed: ^2.3.5
  go_router_builder: ^2.1.1
  json_serializable: ^6.7.0
  melos: ^3.1.0
  pedantic_mono: ^1.22.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2

dependency_overrides:
  # melosが `http ^0.13.1`に依存しているが`dev_dependencies`でユーザー影響が無いためoverridesする
  # google_fonts ^5.0.0 and melos ^3.1.0
  http: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: assets/img/appicon.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
