name: nippo
description: This is a daily report app, and it's a sample app using Flutter and Firebase.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '^3.0.0'

dependencies:
  adaptive_dialog: ^1.9.0+2
  adaptive_theme: ^3.4.1
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.8.3
  cloud_firestore_odm: ^1.0.0-dev.75
  cupertino_icons: ^1.0.5
  # 未マージのためgit指定
  # ref. https://github.com/invertase/flutter_desktop_webview_auth/pull/51
  desktop_webview_auth:
    git: https://github.com/andyshephard/flutter_desktop_webview_auth
  firebase_app_check: ^0.2.1+2
  firebase_auth: ^4.7.0
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^12.1.0
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  hooks_riverpod: ^2.3.6
  intersperse: ^2.0.0
  intl: ^0.18.0
  json_converter_helper: ^0.1.2
  package_info_plus: ^4.1.0
  provider: ^6.0.5
  recase: ^4.1.0
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.2.0
  simple_logger: ^1.9.0+2
  smooth_highlight: ^0.1.1
  tsuruo_kit: ^0.2.0
  url_launcher: ^6.1.12
  version: ^3.0.2

dev_dependencies:
  build_runner: ^2.4.6
  # `cloud_firestore_odm_generator`が無いとReference系の生成がされないので追加
  # ref. https://github.com/firebase/flutterfire/issues/11415#issuecomment-1782381150
  cloud_firestore_odm_generator: ^1.0.0-dev.73
  # riverpod_lint ^1.3.2 requires custom_lint_builder ^0.4.0.
  custom_lint: ^0.4.0
  flutter_gen: ^5.3.1
  flutter_gen_runner: ^5.3.1
  freezed: ^2.4.1
  go_router_builder: ^2.3.4
  json_serializable: ^6.7.1
  melos: ^3.1.1
  pedantic_mono: ^1.23.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2

dependency_overrides:
  # melosが `http ^0.13.1`に依存しているが`dev_dependencies`でユーザー影響が無いためoverridesする
  # google_fonts ^5.0.0 and melos ^3.1.0
  http: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: assets/image/appicon.png

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo/
