name: nippo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '^3.0.0'

dependencies:
  bubble_bottom_bar:
  cloud_firestore:
  cupertino_icons:
  email_validator:
  firebase_analytics:
  firebase_auth:
  firebase_core:
  flutter:
    sdk: flutter
  flutter_overboard:
  flutter_state_notifier:
  freezed_annotation:
  google_fonts:
  google_sign_in:
  intl:
  modal_progress_hud_nsn:
  provider:
  shared_preferences:
  state_notifier:
  url_launcher:

dev_dependencies:
  build_runner:
  freezed:
  json_serializable:
  melos:
  pedantic_mono:

flutter_icons:
  android: true
  ios: true
  image_path: assets/img/appicon.png

flutter:
  uses-material-design: true

  assets:
    - assets/img/ic_main_logo.png
    - assets/img/ic_logo_google.png
    - assets/img/ic_logo_twitter.png
    - assets/img/ic_logo_mail.png
    - assets/img/ic_tutorial_line.png
    - assets/img/profile_dummy.png
